### ISSUE TITLE
I want some way to find finished match after ongoing.

### ISSUE THREAD

**Issue by Qeenon** [w3champions/w3champions-statistic-service#71]
Based on https://github.com/w3champions/w3champions-statistic-service/pull/37

Situation: I track some interesting for me ongoing match and when it's over I want to check it's result.

Currently I can grab all finished matches and find match which has started in same time, having same players, was played one same map, that's not very handy solution.
Ideally I need some GET route where I can use some id provided by ongoing match find finished match. I'm not able to run tests for C# applications because of religion so can't contribute that change.

**Comment by modmoto** [comment]
>  I'm not able to run tests for C# applications because of religion so can't contribute that change.

Welp, I am sorry about that...
