### ISSUE TITLE
Update the wiki with a guide on setting up the dev environment

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-statistic-service#89]
Abeninski gave a lot of info in #new-dev-chat on discord, it would be good to collate this into a dev environment setup guide on the wiki for this repo.

**Comment by modmoto** [comment]
i put a lot of stuff in the readme, also a data seed how you can setup the local database. Is this enough?`

**Comment by Cepheid-UK** [comment]
Ah sorry I missed the readme update, I'll try set up the environment later and see.

**Comment by modmoto** [comment]
I also just set up a unauthorized test db and added a description to reset it, if needed. It is uploading the data right now.
